import React, { useState, useEffect } from "react";
import { useShallow } from "zustand/react/shallow";
import { useChatContextStore } from "@/react_app/store/chatContextStore";
import { useLeverageLoopsStore } from "@/react_app/store/leverageLoopsStore";
import styles from "../CopilotChat.module.scss";

interface LeverageLoopSummaryProps {
  onSendMessage: (message: string) => void;
  isLoading: boolean;
}

export const LeverageLoopSummary: React.FC<LeverageLoopSummaryProps> = ({
  onSendMessage: _onSendMessage,
  isLoading,
}) => {
  const [summaryInput, setSummaryInput] = useState("");
  const [isUpdating, setIsUpdating] = useState(false);

  const { selectedPerson, selectedSuggestionRequest, draftSuggestionRequest, leverageLoopSummaries, upsertLeverageLoopSummary } = useChatContextStore(
    useShallow((state) => ({
      selectedPerson: state.selectedPerson,
      selectedSuggestionRequest: state.selectedSuggestionRequest,
      draftSuggestionRequest: state.draftSuggestionRequest,
      leverageLoopSummaries: state.leverageLoopSummaries,
      upsertLeverageLoopSummary: state.upsertLeverageLoopSummary,
    }))
  );
  
  // Use draft if available, otherwise fall back to selected
  const activeSuggestionRequest = draftSuggestionRequest || selectedSuggestionRequest;

  // Load existing summary when person or suggestion request changes
  // Summary is now generated by the LLM and stored in leverageLoopSummaries
  useEffect(() => {
    let summaryId: string | null = null;
    
    if (selectedPerson) {
      summaryId = selectedPerson.full_name;
    } else if (selectedSuggestionRequest) {
      summaryId = selectedSuggestionRequest.request_header_title;
    }
    
    if (summaryId) {
      const existingSummary = leverageLoopSummaries.find((s) => s.id === summaryId);
      // Use the AI-generated summary from the store
      setSummaryInput(existingSummary?.content || "");
    } else {
      setSummaryInput("");
    }
  }, [selectedPerson, selectedSuggestionRequest, leverageLoopSummaries]);

  const getTitle = () => {
    if (selectedPerson) {
      return `Leverage loop summary for ${selectedPerson.full_name}`;
    }
    if (selectedSuggestionRequest) {
      return selectedSuggestionRequest.request_header_title;
    }
    return "Leverage Loops";
  };

  const handleSubmit = async () => {
    if (summaryInput.trim() && activeSuggestionRequest?.id) {
      setIsUpdating(true);
      try {
        // Update the suggestion request with the summary in request_context
        await useLeverageLoopsStore.getState().updateSuggestionRequest(
          activeSuggestionRequest.id,
          { ...activeSuggestionRequest, request_context: summaryInput.trim(), status: "submitted" }
        );
        // Store is updated by updateSuggestionRequest
      } finally {
        setIsUpdating(false);
      }
    }
  };
  const handleUpdateSummary = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setSummaryInput(e.target.value);
    if(selectedPerson) {
      upsertLeverageLoopSummary({ id: selectedPerson.full_name, content: e.target.value, timestamp: new Date() });
    }
    if(selectedSuggestionRequest) {
      upsertLeverageLoopSummary({ id: selectedSuggestionRequest.request_header_title, content: e.target.value, timestamp: new Date() });
    }
  };

  return (
    <div className={styles.leverageLoopSummary}>
      <div className={styles.summaryCard}>
        <div className={styles.summaryCardHeader}>
          <p className={styles.summaryCardTitle}>{getTitle()}</p>
          <button
            className={styles.summaryCardButton}
            onClick={handleSubmit}
            disabled={!summaryInput.trim() || isLoading || isUpdating}
          >
            {isUpdating ? (
              <span className={styles.loader}></span>
            ) : (
              <span className={styles.playIcon}>▶</span>
            )}
          </button>
        </div>
        <div className={styles.summaryCardInput}>
          <textarea
            className={styles.summaryTextarea}
            placeholder="Summary of what I can help you with..."
            value={summaryInput}
            onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) => handleUpdateSummary(e)}
            rows={2}
          />
        </div>
      </div>
    </div>
  );
};

