type ThemeMode = "light" | "dark" | "system";

export const theme = {
  "fontBody": "400 16px/1.5 Figtree, system-ui, sans-serif",
  "fontBodyLetterSpacing": "0px",
  "fontBodyLink": "400 16px/1.5 Figtree, system-ui, sans-serif",
  "fontBodyLinkLetterSpacing": "0px",
  "fontBodyHeavy": "500 16px/1.5 Figtree, system-ui, sans-serif",
  "fontBodyHeavyLetterSpacing": "0px",
  "fontBodyMedium": "400 16px/1.5 Figtree, system-ui, sans-serif",
  "fontBodyMediumLetterSpacing": "0px",
  "fontBodySmallHeavy": "500 14px/1.5 Figtree, system-ui, sans-serif",
  "fontBodySmallHeavyLetterSpacing": "0px",
  "fontBodySmall": "400 14px/1.5 Figtree, system-ui, sans-serif",
  "fontBodySmallLetterSpacing": "0px",
  "fontBodyLarge": "400 18px/1.5 Figtree, system-ui, sans-serif",
  "fontBodyLargeLetterSpacing": "0px",
  "fontBodyLargeHeavy": "500 18px/1.5 Figtree, system-ui, sans-serif",
  "fontBodyLargeHeavyLetterSpacing": "0px",
  "backgroundFills": "#FAF1F3",
  "containerFills": "rgb(251,247,248)",
  "primaryText": "rgba(48, 35, 35, 1)",
  "secondaryText": "rgba(48, 35, 35, 0.5)",
  "interactiveAccent": "rgba(225, 29, 72, 1)",
  "chatContainerBg": "rgb(246, 240, 242)",
  "chatAssistantResponseBg": "rgb(251,247,248)",
  "chatAssistantResponseText": "rgba(48, 35, 35, 1)",
  "chatUserResponseBg": "rgba(255, 0, 55, 0.1)",
  "chatUserResponseText": "rgba(48, 35, 35, 1)",
};

export const darkTheme = {
  "fontBody": "400 16px/1.5 Figtree, system-ui, sans-serif",
  "fontBodyLetterSpacing": "0px",
  "fontBodyLink": "400 16px/1.5 Figtree, system-ui, sans-serif",
  "fontBodyLinkLetterSpacing": "0px",
  "fontBodyHeavy": "500 16px/1.5 Figtree, system-ui, sans-serif",
  "fontBodyHeavyLetterSpacing": "0px",
  "fontBodyMedium": "375 16px/1.5 system-ui, sans-serif",
  "fontBodyMediumLetterSpacing": "0px",
  "fontBodySmallHeavy": "500 14px/1.5 Figtree, system-ui, sans-serif",
  "fontBodySmallHeavyLetterSpacing": "0px",
  "fontBodySmall": "400 14px/1.5 Figtree, system-ui, sans-serif",
  "fontBodySmallLetterSpacing": "0px",
  "fontBodyLarge": "400 18px/1.5 Figtree, system-ui, sans-serif",
  "fontBodyLargeLetterSpacing": "0px",
  "fontBodyLargeHeavy": "500 18px/1.5 Figtree, system-ui, sans-serif",
  "fontBodyLargeHeavyLetterSpacing": "0px",
  "backgroundFills": "#0E0E0E",
  "containerFills": "#171113",
  "primaryText": "rgba(249, 236, 241, 1)",
  "secondaryText": "rgba(249, 236, 241, 0.5)",
  "interactiveAccent": "rgba(225, 29, 72, 1)",
  "chatContainerBg": "#0E0E0E",
  "chatAssistantResponseBg": "#171113",
  "chatAssistantResponseText": "rgba(249, 236, 241, 1)",
  "chatUserResponseBg": "rgb(57, 31, 37)",
  "chatUserResponseText": "#FFFFFF",
};

export const themeMode: ThemeMode = "dark";

